@host = http://localhost:5062
@token = PON_AQUI_EL_TOKEN

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "demo@tb.com",
  "password": "secret1"
}

### Me
GET {{host}}/api/me
Authorization: Bearer {{token}}

### Add Favorite (Inception)
POST {{host}}/api/favorites
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "publicId": "MOV-INCEPTION"
}

### List Favorites
GET {{host}}/api/favorites
Authorization: Bearer {{token}}
